// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/dmpbean.proto

package models.protobuf.tracker;

public interface DMPBeanOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string end_point_url = 1;
  /**
   * <code>optional string end_point_url = 1;</code>
   */
  boolean hasEndPointUrl();
  /**
   * <code>optional string end_point_url = 1;</code>
   */
  String getEndPointUrl();
  /**
   * <code>optional string end_point_url = 1;</code>
   */
  com.google.protobuf.ByteString
      getEndPointUrlBytes();

  // optional string request_header = 2;
  /**
   * <code>optional string request_header = 2;</code>
   */
  boolean hasRequestHeader();
  /**
   * <code>optional string request_header = 2;</code>
   */
  String getRequestHeader();
  /**
   * <code>optional string request_header = 2;</code>
   */
  com.google.protobuf.ByteString
      getRequestHeaderBytes();

  // optional string request_body = 3;
  /**
   * <code>optional string request_body = 3;</code>
   */
  boolean hasRequestBody();
  /**
   * <code>optional string request_body = 3;</code>
   */
  String getRequestBody();
  /**
   * <code>optional string request_body = 3;</code>
   */
  com.google.protobuf.ByteString
      getRequestBodyBytes();
}
