// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/dmpbean.proto

package models.protobuf.tracker;

/**
 * Protobuf type {@code DMPBean}
 */
public  final class DMPBean extends
    com.google.protobuf.GeneratedMessage
    implements DMPBeanOrBuilder {
  // Use DMPBean.newBuilder() to construct.
  private DMPBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DMPBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DMPBean defaultInstance;
  public static DMPBean getDefaultInstance() {
    return defaultInstance;
  }

  public DMPBean getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DMPBean(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            endPointUrl_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            requestHeader_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            requestBody_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return models.protobuf.tracker.DMPBeanProtos.internal_static_DMPBean_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return models.protobuf.tracker.DMPBeanProtos.internal_static_DMPBean_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            models.protobuf.tracker.DMPBean.class, models.protobuf.tracker.DMPBean.Builder.class);
  }

  public static com.google.protobuf.Parser<DMPBean> PARSER =
      new com.google.protobuf.AbstractParser<DMPBean>() {
    public DMPBean parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DMPBean(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<DMPBean> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string end_point_url = 1;
  public static final int END_POINT_URL_FIELD_NUMBER = 1;
  private Object endPointUrl_;
  /**
   * <code>optional string end_point_url = 1;</code>
   */
  public boolean hasEndPointUrl() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string end_point_url = 1;</code>
   */
  public String getEndPointUrl() {
    Object ref = endPointUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        endPointUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string end_point_url = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEndPointUrlBytes() {
    Object ref = endPointUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      endPointUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string request_header = 2;
  public static final int REQUEST_HEADER_FIELD_NUMBER = 2;
  private Object requestHeader_;
  /**
   * <code>optional string request_header = 2;</code>
   */
  public boolean hasRequestHeader() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string request_header = 2;</code>
   */
  public String getRequestHeader() {
    Object ref = requestHeader_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        requestHeader_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string request_header = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRequestHeaderBytes() {
    Object ref = requestHeader_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      requestHeader_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string request_body = 3;
  public static final int REQUEST_BODY_FIELD_NUMBER = 3;
  private Object requestBody_;
  /**
   * <code>optional string request_body = 3;</code>
   */
  public boolean hasRequestBody() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string request_body = 3;</code>
   */
  public String getRequestBody() {
    Object ref = requestBody_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        requestBody_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string request_body = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRequestBodyBytes() {
    Object ref = requestBody_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      requestBody_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    endPointUrl_ = "";
    requestHeader_ = "";
    requestBody_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getEndPointUrlBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getRequestHeaderBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getRequestBodyBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getEndPointUrlBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getRequestHeaderBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getRequestBodyBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static models.protobuf.tracker.DMPBean parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static models.protobuf.tracker.DMPBean parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static models.protobuf.tracker.DMPBean parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static models.protobuf.tracker.DMPBean parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static models.protobuf.tracker.DMPBean parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static models.protobuf.tracker.DMPBean parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static models.protobuf.tracker.DMPBean parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static models.protobuf.tracker.DMPBean parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static models.protobuf.tracker.DMPBean parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static models.protobuf.tracker.DMPBean parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(models.protobuf.tracker.DMPBean prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DMPBean}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements models.protobuf.tracker.DMPBeanOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return models.protobuf.tracker.DMPBeanProtos.internal_static_DMPBean_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return models.protobuf.tracker.DMPBeanProtos.internal_static_DMPBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              models.protobuf.tracker.DMPBean.class, models.protobuf.tracker.DMPBean.Builder.class);
    }

    // Construct using models.protobuf.tracker.DMPBean.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      endPointUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      requestHeader_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      requestBody_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return models.protobuf.tracker.DMPBeanProtos.internal_static_DMPBean_descriptor;
    }

    public models.protobuf.tracker.DMPBean getDefaultInstanceForType() {
      return models.protobuf.tracker.DMPBean.getDefaultInstance();
    }

    public models.protobuf.tracker.DMPBean build() {
      models.protobuf.tracker.DMPBean result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public models.protobuf.tracker.DMPBean buildPartial() {
      models.protobuf.tracker.DMPBean result = new models.protobuf.tracker.DMPBean(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.endPointUrl_ = endPointUrl_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.requestHeader_ = requestHeader_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.requestBody_ = requestBody_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof models.protobuf.tracker.DMPBean) {
        return mergeFrom((models.protobuf.tracker.DMPBean)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(models.protobuf.tracker.DMPBean other) {
      if (other == models.protobuf.tracker.DMPBean.getDefaultInstance()) return this;
      if (other.hasEndPointUrl()) {
        bitField0_ |= 0x00000001;
        endPointUrl_ = other.endPointUrl_;
        onChanged();
      }
      if (other.hasRequestHeader()) {
        bitField0_ |= 0x00000002;
        requestHeader_ = other.requestHeader_;
        onChanged();
      }
      if (other.hasRequestBody()) {
        bitField0_ |= 0x00000004;
        requestBody_ = other.requestBody_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      models.protobuf.tracker.DMPBean parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (models.protobuf.tracker.DMPBean) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string end_point_url = 1;
    private Object endPointUrl_ = "";
    /**
     * <code>optional string end_point_url = 1;</code>
     */
    public boolean hasEndPointUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string end_point_url = 1;</code>
     */
    public String getEndPointUrl() {
      Object ref = endPointUrl_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        endPointUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string end_point_url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEndPointUrlBytes() {
      Object ref = endPointUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endPointUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string end_point_url = 1;</code>
     */
    public Builder setEndPointUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      endPointUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string end_point_url = 1;</code>
     */
    public Builder clearEndPointUrl() {
      bitField0_ = (bitField0_ & ~0x00000001);
      endPointUrl_ = getDefaultInstance().getEndPointUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string end_point_url = 1;</code>
     */
    public Builder setEndPointUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      endPointUrl_ = value;
      onChanged();
      return this;
    }

    // optional string request_header = 2;
    private Object requestHeader_ = "";
    /**
     * <code>optional string request_header = 2;</code>
     */
    public boolean hasRequestHeader() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string request_header = 2;</code>
     */
    public String getRequestHeader() {
      Object ref = requestHeader_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        requestHeader_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string request_header = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRequestHeaderBytes() {
      Object ref = requestHeader_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestHeader_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string request_header = 2;</code>
     */
    public Builder setRequestHeader(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      requestHeader_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_header = 2;</code>
     */
    public Builder clearRequestHeader() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestHeader_ = getDefaultInstance().getRequestHeader();
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_header = 2;</code>
     */
    public Builder setRequestHeaderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      requestHeader_ = value;
      onChanged();
      return this;
    }

    // optional string request_body = 3;
    private Object requestBody_ = "";
    /**
     * <code>optional string request_body = 3;</code>
     */
    public boolean hasRequestBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string request_body = 3;</code>
     */
    public String getRequestBody() {
      Object ref = requestBody_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        requestBody_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string request_body = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequestBodyBytes() {
      Object ref = requestBody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string request_body = 3;</code>
     */
    public Builder setRequestBody(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      requestBody_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_body = 3;</code>
     */
    public Builder clearRequestBody() {
      bitField0_ = (bitField0_ & ~0x00000004);
      requestBody_ = getDefaultInstance().getRequestBody();
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_body = 3;</code>
     */
    public Builder setRequestBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      requestBody_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:DMPBean)
  }

  static {
    defaultInstance = new DMPBean(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:DMPBean)
}

